### ISSUE TITLE
Cannot find module 'findup-sync'

### ISSUE THREAD

**Issue by joshhornby** [larsonjj/generator-yeogurt#124]
When trying to run ```grunt serve``` on a fresh install I get the following error

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'findup-sync'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:8:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Set up like so:

```
{
  "generator-yeogurt": {
    "config": {
      "projectName": "Favourite",
      "versionControl": "git",
      "useServer": true,
      "dbOption": "sql",
      "dbHost": "localhost",
      "dbPort": "3306",
      "dbName": "favourite",
      "dbUser": "homestead",
      "dbPass": "secret",
      "useAuth": false,
      "singlePageApplication": true,
      "jsFramework": "react",
      "useJsx": true,
      "cssOption": "sass",
      "sassSyntax": "scss",
      "useJsdoc": true,
      "useKss": true,
      "useTesting": true,
      "testFramework": "jasmine",
      "dbType": "mysql",
      "jsOption": "browserify"
    },
    "version": "0.14.4"
  }
}
```

**Comment by joshhornby** [comment]
Sorry should of Googled first

This fixed it 

http://stackoverflow.com/questions/15444020/cannot-find-module-findup-sync-when-trying-to-run-grunt
