### ISSUE TITLE
gulp serve crashes when I'm renaming folder

### ISSUE THREAD

**Issue by eko24** [larsonjj/generator-yeogurt#183]
Here is what I get in terminal when I'm renaming folder or file:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch ENOENT
    at exports._errnoException (util.js:837:11)
    at FSWatcher.start (fs.js:1231:11)
    at Object.fs.watch (fs.js:1257:11)
    at Gaze._watchDir (D:\workspace\ftr\node_modules\gaze\lib\gaze.js:289:30)
    at D:\workspace\ftr\node_modules\gaze\lib\gaze.js:358:10
    at iterate (D:\workspace\ftr\node_modules\gaze\lib\helper.js:52:5)
    at D:\workspace\ftr\node_modules\gaze\lib\helper.js:61:11
    at D:\workspace\ftr\node_modules\gaze\lib\gaze.js:420:5
    at iterate (D:\workspace\ftr\node_modules\gaze\lib\helper.js:52:5)
    at D:\workspace\ftr\node_modules\gaze\lib\helper.js:61:11
```

**Comment by larsonjj** [comment]
Hey @eko24, This is a gulp v3 problem ([source](https://github.com/gulpjs/gulp/issues/651))

Once Gulp 4 comes out, it should be fixed. In the meantime, just restart your `gulp serve`.
